# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Component.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Shared_pb2 as Shared__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Component.proto',
  package='Scynet',
  syntax='proto3',
  serialized_options=_b('\252\002\006Scynet'),
  serialized_pb=_b('\n\x0f\x43omponent.proto\x12\x06Scynet\x1a\x0cShared.proto\"/\n\x11\x41gentStartRequest\x12\x1a\n\x03\x65gg\x18\x02 \x01(\x0b\x32\r.Scynet.Agent\"\x1c\n\x0c\x41gentRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"\x0c\n\nAgentQuery\"-\n\x0cListOfAgents\x12\x1d\n\x06\x61gents\x18\x01 \x03(\x0b\x32\r.Scynet.Agent\"&\n\x13\x41gentStatusResponse\x12\x0f\n\x07running\x18\x01 \x01(\x08\x32\xf4\x01\n\tComponent\x12\x37\n\nAgentStart\x12\x19.Scynet.AgentStartRequest\x1a\x0c.Scynet.Void\"\x00\x12\x31\n\tAgentStop\x12\x14.Scynet.AgentRequest\x1a\x0c.Scynet.Void\"\x00\x12\x42\n\x0b\x41gentStatus\x12\x14.Scynet.AgentRequest\x1a\x1b.Scynet.AgentStatusResponse\"\x00\x12\x37\n\tAgentList\x12\x12.Scynet.AgentQuery\x1a\x14.Scynet.ListOfAgents\"\x00\x42\t\xaa\x02\x06Scynetb\x06proto3')
  ,
  dependencies=[Shared__pb2.DESCRIPTOR,])




_AGENTSTARTREQUEST = _descriptor.Descriptor(
  name='AgentStartRequest',
  full_name='Scynet.AgentStartRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='egg', full_name='Scynet.AgentStartRequest.egg', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=88,
)


_AGENTREQUEST = _descriptor.Descriptor(
  name='AgentRequest',
  full_name='Scynet.AgentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='Scynet.AgentRequest.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=118,
)


_AGENTQUERY = _descriptor.Descriptor(
  name='AgentQuery',
  full_name='Scynet.AgentQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=132,
)


_LISTOFAGENTS = _descriptor.Descriptor(
  name='ListOfAgents',
  full_name='Scynet.ListOfAgents',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='agents', full_name='Scynet.ListOfAgents.agents', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=179,
)


_AGENTSTATUSRESPONSE = _descriptor.Descriptor(
  name='AgentStatusResponse',
  full_name='Scynet.AgentStatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='running', full_name='Scynet.AgentStatusResponse.running', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=181,
  serialized_end=219,
)

_AGENTSTARTREQUEST.fields_by_name['egg'].message_type = Shared__pb2._AGENT
_LISTOFAGENTS.fields_by_name['agents'].message_type = Shared__pb2._AGENT
DESCRIPTOR.message_types_by_name['AgentStartRequest'] = _AGENTSTARTREQUEST
DESCRIPTOR.message_types_by_name['AgentRequest'] = _AGENTREQUEST
DESCRIPTOR.message_types_by_name['AgentQuery'] = _AGENTQUERY
DESCRIPTOR.message_types_by_name['ListOfAgents'] = _LISTOFAGENTS
DESCRIPTOR.message_types_by_name['AgentStatusResponse'] = _AGENTSTATUSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AgentStartRequest = _reflection.GeneratedProtocolMessageType('AgentStartRequest', (_message.Message,), dict(
  DESCRIPTOR = _AGENTSTARTREQUEST,
  __module__ = 'Component_pb2'
  # @@protoc_insertion_point(class_scope:Scynet.AgentStartRequest)
  ))
_sym_db.RegisterMessage(AgentStartRequest)

AgentRequest = _reflection.GeneratedProtocolMessageType('AgentRequest', (_message.Message,), dict(
  DESCRIPTOR = _AGENTREQUEST,
  __module__ = 'Component_pb2'
  # @@protoc_insertion_point(class_scope:Scynet.AgentRequest)
  ))
_sym_db.RegisterMessage(AgentRequest)

AgentQuery = _reflection.GeneratedProtocolMessageType('AgentQuery', (_message.Message,), dict(
  DESCRIPTOR = _AGENTQUERY,
  __module__ = 'Component_pb2'
  # @@protoc_insertion_point(class_scope:Scynet.AgentQuery)
  ))
_sym_db.RegisterMessage(AgentQuery)

ListOfAgents = _reflection.GeneratedProtocolMessageType('ListOfAgents', (_message.Message,), dict(
  DESCRIPTOR = _LISTOFAGENTS,
  __module__ = 'Component_pb2'
  # @@protoc_insertion_point(class_scope:Scynet.ListOfAgents)
  ))
_sym_db.RegisterMessage(ListOfAgents)

AgentStatusResponse = _reflection.GeneratedProtocolMessageType('AgentStatusResponse', (_message.Message,), dict(
  DESCRIPTOR = _AGENTSTATUSRESPONSE,
  __module__ = 'Component_pb2'
  # @@protoc_insertion_point(class_scope:Scynet.AgentStatusResponse)
  ))
_sym_db.RegisterMessage(AgentStatusResponse)


DESCRIPTOR._options = None

_COMPONENT = _descriptor.ServiceDescriptor(
  name='Component',
  full_name='Scynet.Component',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=222,
  serialized_end=466,
  methods=[
  _descriptor.MethodDescriptor(
    name='AgentStart',
    full_name='Scynet.Component.AgentStart',
    index=0,
    containing_service=None,
    input_type=_AGENTSTARTREQUEST,
    output_type=Shared__pb2._VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AgentStop',
    full_name='Scynet.Component.AgentStop',
    index=1,
    containing_service=None,
    input_type=_AGENTREQUEST,
    output_type=Shared__pb2._VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AgentStatus',
    full_name='Scynet.Component.AgentStatus',
    index=2,
    containing_service=None,
    input_type=_AGENTREQUEST,
    output_type=_AGENTSTATUSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AgentList',
    full_name='Scynet.Component.AgentList',
    index=3,
    containing_service=None,
    input_type=_AGENTQUERY,
    output_type=_LISTOFAGENTS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_COMPONENT)

DESCRIPTOR.services_by_name['Component'] = _COMPONENT

# @@protoc_insertion_point(module_scope)
