# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Shared.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Shared.proto',
  package='Scynet',
  syntax='proto3',
  serialized_options=_b('\252\002\006Scynet'),
  serialized_pb=_b('\n\x0cShared.proto\x12\x06Scynet\"b\n\x05\x41gent\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0f\n\x07\x65ggData\x18\x02 \x01(\x0c\x12\x15\n\rcomponentType\x18\x03 \x01(\t\x12\x13\n\x0b\x63omponentId\x18\x04 \x01(\t\x12\x0e\n\x06inputs\x18\x06 \x03(\t\"\x06\n\x04VoidB\t\xaa\x02\x06Scynetb\x06proto3')
)




_AGENT = _descriptor.Descriptor(
  name='Agent',
  full_name='Scynet.Agent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='Scynet.Agent.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='eggData', full_name='Scynet.Agent.eggData', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='componentType', full_name='Scynet.Agent.componentType', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='componentId', full_name='Scynet.Agent.componentId', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inputs', full_name='Scynet.Agent.inputs', index=4,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=122,
)


_VOID = _descriptor.Descriptor(
  name='Void',
  full_name='Scynet.Void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=130,
)

DESCRIPTOR.message_types_by_name['Agent'] = _AGENT
DESCRIPTOR.message_types_by_name['Void'] = _VOID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Agent = _reflection.GeneratedProtocolMessageType('Agent', (_message.Message,), dict(
  DESCRIPTOR = _AGENT,
  __module__ = 'Shared_pb2'
  # @@protoc_insertion_point(class_scope:Scynet.Agent)
  ))
_sym_db.RegisterMessage(Agent)

Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), dict(
  DESCRIPTOR = _VOID,
  __module__ = 'Shared_pb2'
  # @@protoc_insertion_point(class_scope:Scynet.Void)
  ))
_sym_db.RegisterMessage(Void)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
