apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-rest
  namespace: kafka-add
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-rest
  template:
    metadata:
      labels:
        app: kafka-rest
    spec:
      containers:
      - name: broker
        image: confluentinc/cp-kafka-rest:5.0.1
        env:
        - name: KAFKA_REST_ZOOKEEPER_CONNECT
          value: zookeeper.kafka
        - name: KAFKA_REST_SCHEMA_REGISTRY_URL
          value: http://schema-registry.kafka-add:80
        - name: KAFKA_REST_HOST_NAME
          value: kafka-rest
        - name: KAFKA_REST_LISTENERS
          value: http://0.0.0.0:8082
        ports:
        - containerPort: 8082
        # HACK: Since schema registry uses KAFKA_REST_PORT for configuration, we have to unset the one from kubernetes
        command: ["bash", "-c", "unset KAFKA_REST_PORT; /etc/confluent/docker/run"]
