apiVersion: v1
kind: Service
metadata:
  name: parity
  namespace: parity
spec:
  ports:
  - port: 5001
    name: ipfs
  - port: 8080
    name: ui-maybe
  - port: 8082
    name: secrets-1
  - port: 8083
    name: secrets-2
  - port: 8545
    name: rpc
  - port: 8546
    name: ws
  - port: 8180
    name: ui-deprecated
  selector:
    app: parity
